In [1]:
import numpy as np

№1

In [24]:
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
print("исходник ")
print(m)
print("T1: ")
print(m.T)
print("T2: ")
o = (m.T).T
print(o)

исходник 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
T1: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
T2: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


№2

In [25]:
m2 = np.matrix('1 9 4; 10 5 5; 12 7 8')
print(m)
print(m2)

print("Транспонирование суммы матриц:")
o1 = (m + m2).T
print(o1)

print("Сумма транспонированных матриц:")
o2 = m.T + m2.T
print(o2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
Транспонирование суммы матриц:
[[ 2 14 19]
 [11 10 15]
 [ 7 11 17]]
Сумма транспонированных матриц:
[[ 2 14 19]
 [11 10 15]
 [ 7 11 17]]


№3

In [26]:
print(m)
print(m2)

print("Транспонирование произведения матриц:")
o1 = (m.dot(m2)).T
print(o1)

print("Произведение транспонированных матриц:")
o2 = (m2.T).dot(m.T)
print(o2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
Транспонирование произведения матриц:
[[ 57 126 195]
 [ 40 103 166]
 [ 38  89 140]]
Произведение транспонированных матриц:
[[ 57 126 195]
 [ 40 103 166]
 [ 38  89 140]]


№4

In [27]:
print(m)
p = 2
print(p)

print("Транспонирование произведения матрицы на число:")
o1 =  (p * m).T
print(o1)

print("Произведение числа на транспонированную матрицу:")
o2 =  p * (m.T)
print(o2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
Транспонирование произведения матрицы на число:
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
Произведение числа на транспонированную матрицу:
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


№5

In [30]:
m = np.matrix('2 0 4; 11 4 5; 15 3 4')
print(m)

print("определитель исходной матрицы:")
opr = np.linalg.det(m)
print(format(opr, '.3g'))

print("определитель транспонированной матрицы:")
opr2 = np.linalg.det(m.T)
print(format(opr2, '.3g'))

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
определитель исходной матрицы:
-106
определитель транспонированной матрицы:
-106


Действия над матрицамт

№1

In [33]:
print(m)

print("произведение единицы и матрицы:")
o = 1 * m
print(o)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
произведение единицы и матрицы:
[[ 2  0  4]
 [11  4  5]
 [15  3  4]]


№2

In [37]:
m0 = np.matrix('0 0 0; 0 0 0; 0 0 0')
print(m)
o = 0 * m
print("Нулевая матрица:")
print(m0)
print("Произведение матрицы на 0:")
print(o)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
Нулевая матрица:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Произведение матрицы на 0:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


№3

In [38]:
print(m)
print("\nПроизведение матрицы на сумму чисел:")
o = (6 + 2) * m
print(o)
print("Произведений матрицы на каждое из этих чисел:")
o2 = 6 * m + 2 * m
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]

Произведение матрицы на сумму чисел:
[[ 16   0  32]
 [ 88  32  40]
 [120  24  32]]
Произведений матрицы на каждое из этих чисел:
[[ 16   0  32]
 [ 88  32  40]
 [120  24  32]]


№4

In [39]:
print(m)
print("\nПроизведение матрицы на произведение чисел:")
o = (7 * 2) * m
print(o)

print("Произведений второго числа и заданной матрицы, умноженному на первое число:")
o2 = 7 * (2 * m)
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]

Произведение матрицы на произведение чисел:
[[ 28   0  56]
 [154  56  70]
 [210  42  56]]
Произведений второго числа и заданной матрицы, умноженному на первое число:
[[ 28   0  56]
 [154  56  70]
 [210  42  56]]


№5

In [40]:
print(m)
print(m2)
k = 5
print(k)

print("\nПроизведение суммы матриц на число:")
o = k * (m + m2)
print(o)

print("\nCуммa произведений этих матриц на заданное число:")
o2 = k * m + k * m2
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
5

Произведение суммы матриц на число:
[[ 15  45  40]
 [105  45  50]
 [135  50  60]]

Cуммa произведений этих матриц на заданное число:
[[ 15  45  40]
 [105  45  50]
 [135  50  60]]


сложение матриц

№1

In [42]:
print(m)
print(m2)

print("\nm + m2")
o = m + m2
print(o)
print("\nm2 + m")
o2 = m2 + m
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]

m + m2
[[ 3  9  8]
 [21  9 10]
 [27 10 12]]

m2 + m
[[ 3  9  8]
 [21  9 10]
 [27 10 12]]


№2

In [43]:
m3 = np.matrix('5 1 7; 4 3 2; 2 5 6')
print(m)
print(m2)
print(m3)

print("\nm + (m2 + m3)")
o = m + (m2 + m3)
print(o)
print("\n(m + m2) + m3")
o2 = (m + m2) + m3
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
[[5 1 7]
 [4 3 2]
 [2 5 6]]

m + (m2 + m3)
[[ 8 10 15]
 [25 12 12]
 [29 15 18]]

(m + m2) + m3
[[ 8 10 15]
 [25 12 12]
 [29 15 18]]


№3

In [44]:
print(m)

print(f"m:\n{A}")
print(f"-m:\n{m * (-1)}")

print(f"сумма:")
o = m + (-1)*m
print(o)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
m:
[[ 8  1  5]
 [ 7  7  1]
 [ 0  9 18]]
-m:
[[ -2   0  -4]
 [-11  -4  -5]
 [-15  -3  -4]]
сумма:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Умножение матриц

№1

In [45]:
print(m)
print(m2)
print(m3)

print("m*(m2*m3)")
o = m.dot(m2.dot(m3))
print(o)
print("(m*m2)*m3")
o2 = (m.dot(m2)).dot(m3)
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
[[5 1 7]
 [4 3 2]
 [2 5 6]]
m*(m2*m3)
[[ 514  388  682]
 [1379 1093 1709]
 [1391 1162 1649]]
(m*m2)*m3
[[ 514  388  682]
 [1379 1093 1709]
 [1391 1162 1649]]


№2

In [47]:
print(m)
print(m2)
print(m3)

print("m * (m2+m3)")
o = m.dot(m2 + m3)
print(o)
print("m*m2 + m*m3)")
o2 = m.dot(m2) + m.dot(m3)
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
[[5 1 7]
 [4 3 2]
 [2 5 6]]
m * (m2+m3)
[[ 68  68  78]
 [192 202 219]
 [188 222 242]]
m*m2 + m*m3)
[[ 68  68  78]
 [192 202 219]
 [188 222 242]]


№3

In [48]:
print(m)
print(m2)
      
print("m*m2")
o = m.dot(m2)
print(o)
print("m2*m")
o2 = m2.dot(m)
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
[[ 1  9  4]
 [10  5  5]
 [12  7  8]]
m*m2
[[ 50  46  40]
 [111 154 104]
 [ 93 178 107]]
m2*m
[[161  48  65]
 [150  35  85]
 [221  52 115]]


№4

In [49]:

e = np.eye(3)
print(m)

print("e*m")
Lo = e.dot(m)
print(o)
print("m*e")
Ro2 = m.dot(e)
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
e*m
[[ 50  46  40]
 [111 154 104]
 [ 93 178 107]]
m*e
[[161  48  65]
 [150  35  85]
 [221  52 115]]


№5

In [50]:
e = np.zeros((3, 3))
print(m)

print("e*m")
o = e.dot(m)
print(o)
print("m*e")
o2 = m.dot(e)
print(o2)

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
e*m
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
m*e
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Определитель матрицы

№1  Определитель матрицы остается неизменным при ее транспонировании:

In [51]:

print(m)
opr = round(np.linalg.det(m), 3)
print(f"|m| = {opr}\n")

print(f"m(T):\n{m.T}\n")
oprt = round(np.linalg.det(m.T), 3)
print(f"|m(T)| = {oprt}")

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
|m| = -106.0

m(T):
[[ 2 11 15]
 [ 0  4  3]
 [ 4  5  4]]

|m(T)| = -106.0


№2 Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [53]:
print(m)
opr = round(np.linalg.det(m), 3)
print(f"|m| = {opr}\n")

m4 = np.matrix('0 2 0; 0 5 1; 0 1 1')
print(m4)

opr = round(np.linalg.det(m4), 3)
print(f"|m4| = {opr}\n")

m4 = np.matrix('0 0 0; 1 1 1;2 2 2')
print(m4)
opr = round(np.linalg.det(m4), 3)
print(f"|m4| = {opr}\n")

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
|m| = -106.0

[[0 2 0]
 [0 5 1]
 [0 1 1]]
|m4| = 0.0

[[0 0 0]
 [1 1 1]
 [2 2 2]]
|m4| = 0.0



№3 При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [56]:
a = np.matrix('2 0 4; 11 4 5; 15 3 4')
print(a)
opr = round(np.linalg.det(a), 3)
print(f"|a| = {opr}\n")

b = np.matrix('11 4 5; 2 0 4; 15 3 4')
print(b)
opr = round(np.linalg.det(b), 3)
print(f"|b| = {opr}\n")

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
|a| = -106.0

[[11  4  5]
 [ 2  0  4]
 [15  3  4]]
|b| = 106.0



№4 Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [59]:
print(m)
opr = round(np.linalg.det(m), 3)
print(f"|m| = {opr}\n")

a = np.matrix('1 2 3; 1 2 3; 1 1 1')
print(a)
opr = round(np.linalg.det(a), 3)
print(f"|a| = {opr}\n")

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
|m| = -106.0

[[1 2 3]
 [1 2 3]
 [1 1 1]]
|a| = 0.0



№5 Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [62]:
print(m)
k = 2
opr = round(np.linalg.det(m), 3)
print(f"|m| = {opr}")
print(f"|m| * k = {opr * k}\n")

mc = m.copy()
mc[:,0] = k * mc[:,0]
print(mc)

opr = round(np.linalg.det(mc), 3)
print(f"|mc| = {opr}\n")

[[ 2  0  4]
 [11  4  5]
 [15  3  4]]
|m| = -106.0
|m| * k = -212.0

[[ 4  0  4]
 [22  4  5]
 [30  3  4]]
|mc| = -212.0



№6  Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [67]:
m1 = np.matrix('2 2 4 ; -3 4 -1; 8 8 10 ')
m2 = np.matrix('2 2 4; 6 8 2; 8 8 10')
m3 = m1.copy()
m3[1, :] += m2[1, :]
print("m3")
print(m3)
print("m1")
print(m1)
print("m2")
print(m2)
print("|m3|")
print(round(np.linalg.det(m3), 3))
print("|m1| + |m2|")
print(round(np.linalg.det(m1), 3) + round(np.linalg.det(m2), 3))

m3
[[ 2  2  4]
 [ 3 12  1]
 [ 8  8 10]]
m1
[[ 2  2  4]
 [-3  4 -1]
 [ 8  8 10]]
m2
[[ 2  2  4]
 [ 6  8  2]
 [ 8  8 10]]
|m3|
-108.0
|m1| + |m2|
-108.0


№7 Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [68]:
m1
k = 2

b = m1.copy()
b[1, :] = b[1, :] + k * b[0, :]

print("m1")
print(m1)
print("b")
print(b)

print("|m1|")
print(round(np.linalg.det(m1), 3))
print("|b|")
print(round(np.linalg.det(b), 3))

m1
[[ 2  2  4]
 [-3  4 -1]
 [ 8  8 10]]
b
[[ 2  2  4]
 [ 1  8  7]
 [ 8  8 10]]
|m1|
-84.0
|b|
-84.0


№8 Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю

In [69]:
print("m1")
print(m1)
k = 2
m1[1, :] = m1[0, :] + k * m1[2, :]
print("|m1|")
print(round(np.linalg.det(m1), 3))

m1
[[ 2  2  4]
 [-3  4 -1]
 [ 8  8 10]]
|m1|
0.0


№9  Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [74]:

print("m1")
print(m1)
print(round(np.linalg.det(m1), 3))

k = 2
m1[1, :] = k * m1[0, :]
print("\n novei m1")
print(m1)
print(round(np.linalg.det(m1), 3))

m1
[[ 2  2  4]
 [ 4  4  8]
 [ 8  8 10]]
0.0

 novei m1
[[ 2  2  4]
 [ 4  4  8]
 [ 8  8 10]]
0.0


Обратная матрица

№1 Обратная матрица обратной матрицы есть исходная матрица:

In [80]:
m1 = np.matrix('1 2 ; 4 5 ')
print("m1")
print(m1)
inve = np.linalg.inv(m1)
print("inv")
print(inve)
iii = np.linalg.inv(inve)
print("inveinv")
print(iii)

m1
[[1 2]
 [4 5]]
inv
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
inveinv
[[1. 2.]
 [4. 5.]]


№2 Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [81]:
print(m1)

print("Обратная матрица транспонированной матрицы:")
o = np.linalg.inv(m1.T)
print(o)

print("Транспонированная матрица от обратной матрицы:")
o2 = (np.linalg.inv(m1)).T
print(o2)

[[1 2]
 [4 5]]
Обратная матрица транспонированной матрицы:
[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]
Транспонированная матрица от обратной матрицы:
[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


№3 Обратная матрица произведения матриц равна произведению обратных матриц:

In [83]:
m2 = np.matrix('3 4; 6 7')
print(m1)
print(m2)

print("Обратная матрица произведения матриц:")
o = np.linalg.inv(m1.dot(m2))
print(o)

print("Произведение обратных матриц:")
o2 = np.linalg.inv(m2).dot(np.linalg.inv(m1))
print(o2)

[[1 2]
 [4 5]]
[[3 4]
 [6 7]]
Обратная матрица произведения матриц:
[[ 5.66666667 -2.        ]
 [-4.66666667  1.66666667]]
Произведение обратных матриц:
[[ 5.66666667 -2.        ]
 [-4.66666667  1.66666667]]
